#! /bin/sh
#
# chkconfig 2345 50 50
#
#@Added_by: Okoye Chuka D.<okoye9@gmail.com>
#@desc:     The modified HA-OSCAR rsync daemon

# source function library
 . /etc/rc.d/init.d/functions

PROG='/usr/bin/rsync'
BASE=${0##*/}

OPTIONS="--daemon --config=/etc/rsyncd.conf"

case "$1" in
  start)
      echo -n $"Starting $BASE: "
      daemon --check $BASE $PROG $OPTIONS
      RETVAL=$?
      [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$BASE
      echo
      ;;

 stop)
     echo -n $"Shutting down $BASE: "
     killproc $BASE
     RETVAL=$?
     [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$BASE
     echo
     ;;
 restart|force-reload)
     $0 stop
         sleep 1
             $0 start
               ;;
*)
    echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
            ;;

            esac

exit 0


